---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: dov-cm
  labels:
    app: dov-bear
data: 
  INSTANCE_NAME: name set from config map
  INSTANCE_HASH: 123xyz
---

apiVersion: v1
kind: Pod
metadata:
  name: dov-pod
  labels:
    app: dov-bear
    owner: fred
    dept: enggg
#  namespace: myns
spec:
  containers:
  - name: dov-container
    image: stackupiss/dov-bear:v2
    imagePullPolicy: IfNotPresent
    ports: 
    - name: web
      containerPort: 3000
    envFrom:
    - configMapRef: 
       name: dov-cm