apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./northwind-v2.yaml # targetted k8s file
# - ./nwdb.yaml # targetted k8s file

commonLabels:
  env: testing
  dept: eng

namePrefix: test- # gonna add test- to all your resources in the front

nameSuffix: -v1 # gonna add v1 to all your resources at the back

# namespace: testns

replicas:
- name: nwapp
  count: 2

images:
- name: stackupiss/northwind-app
  newName: siyuantann/northwind-app
  newTag: v2

configMapGenerator:
  - name: nwapp-cm
    behavior: create # create, replace, merge
    literals:
      - DB_USER="fried"
      - DB_PASSWORD="friedfried"
      - LOG_LEVEL="info"

# can only apply a patch in the same resource once
patchesStrategicMerge:
  - patch.yaml

# replacements:
# - source:
#     name: nwdb
#     kind: Service
#     fieldPath: metadata.name
# targets:
#   - select:
#       name: nwapp
#       kind: Deployment
#       fieldPaths: 
#         - spec.template.spec.containers[name=northwind-app].env.[name=DB_HOST].value

