---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: nwapp-cm
#   labels:
#     app: nwapp
# data:
#   DB_USER: root
#   DB_PASSWORD: changeit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nwapp
  name: nwapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nwapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nwapp
    spec:
      containers:
      - image: stackupiss/northwind-app:v1
        name: northwind-app
        env:
        - name: DB_HOST
          value: bggdb-cluster-mysql-master # db cluster
        - name: INSTANCE_IP_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom: 
          - configMapRef:
            name: nwapp-cm
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nwapp
  name: nwapp
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nwapp
  type: ClusterIP
status:
  loadBalancer: {}