---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nwdb
  name: nwdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nwdb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nwdb
    spec:
      containers:
      - image: stackupiss/northwind-app:v1
        name: northwind-db
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nwdb
  name: nwdb
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nwdb
  type: ClusterIP
status:
  loadBalancer: {}