---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wp-pvc
    labels:
      name: wp-pvc
spec:
    accessModes:
      - ReadWriteOnce
    storageClassName: do-block-storage
    resources:
      requests:
        storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:   
  name: wpapp-deploy
  labels:
    app: wp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-pod
  template:
    metadata:
      name: wp-pod
      labels:
        app: wp-pod
    spec:
      volumes:
        - name: wp-vol
          persistentVolumeClaim:
            claimName: wp-pvc
      containers:
        - name: wp-container
          image: wordpress:5.8
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
          envFrom:
          - configMapRef:
              name: wpapp-cm
          - secretRef:
              name: wpdb-secret
          volumeMounts:
          - name: wp-vol
            mountPath: /var/www/html

---
apiVersion: v1
kind: Service
metadata:
    name: wpapp-svc
    labels:
        app: wpapp-svc
spec:
  type: ClusterIP
  selector:
      app: wp-pod
  ports:
    - port: 80
      targetPort: 80
      # any request coming into 8080 will be redirected to 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wpapp-ing
  labels:
    name: wpapp-ing
  annotations:
    nginx.ingress.kubernetes.io/limit-connections: "10"
spec: 
  ingressClassName: nginx
  rules:
    - host: friedrice-wp.144.126.243.118.nip.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: wpapp-svc
              port: 
                number: 80