apiVersion: v1
kind: Secret
metadata:
  name: wpdb-secret
  labels:
    app: wpdb-secret
type: Opaque
data:
  #wordpress
  ROOT_PASSWORD: d29yZHByZXNz
  WORDPRESS_DB_PASSWORD: d29yZHByZXNz
---

apiVersion: v1
kind: ConfigMap
metadata: 
  name: wpapp-cm
  labels:
    app: wpapp-cm
data: 
  WORDPRESS_DB_HOST: wpdb-cluster-mysql-master
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_NAME: wpdb

---